// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver');
// let proxy = require('selenium-webdriver/proxy');
const md5 = require('md5');

function changeTimezone(date, ianatz) {
    let invdate = new Date(date.toLocaleString('en-US', {
        timeZone: ianatz
    }));
    
    let diff = date.getTime() - invdate.getTime();

    return new Date(date.getTime() - diff - (60 * 60 * 5 * 1000));
}

function generateCode(email, date, length = 4) {
    return Number(('' + parseInt(md5('3t65AtXgJnBrYv4d' + email + date + '3t65AtXgJnBrYv4d').substr(0, 10), 16)).substr(0, length))
}

describe('Sign Up', function() {
    this.timeout(0);
    let driver;
    let email = 'humarmorenobravo+test1629739271956@gmail.com';//'humarmorenobravo+test' + new Date().getTime() + '@gmail.com';

    beforeEach(async function() {
        driver = await new Builder().forBrowser('chrome').build();
        await driver.manage().setTimeouts({ implicit: 3000 });
        
        console.log('Navigating to https://dev-www.talent.com/sas...');
        
        await driver.get('https://dev-www.talent.com/sas');
        
        console.log('Adding sas-token...')
        
        await driver.manage().addCookie({ name: 'sas-token', value: 'V0010_bZRTrx8KjmmO90mewWrQ11soxm-35NtwnVCNWgoQo8TkkAjZM39WC7qEwbepDTxdLZWxGeHAiko-Uf1wG4Rg%2A%2A', domain: '.talent.com', httpOnly: true});
        
        console.log('Navigating to https://dev-www.talent.com/...');
        
        await driver.get('https://dev-www.talent.com/');
        
        await driver.manage().window().setRect(1287, 580);

        vars = {};
    });

    afterEach(async function() {
        await driver.quit();
    });

    it('Sign Up', async function() {

        let date = changeTimezone(new Date(), 'America/Toronto');
        let dateFirst = date.toJSON().split('T').join(' ').substr(0, 15);
        let dateSecond = (new Date(date.getTime() - 60 * 10 * 1000)).toJSON().split('T').join(' ').substr(0, 15);

        let code1 = generateCode(email, dateFirst);
        let code2 = generateCode(email, dateSecond);

        
        console.log('Clicking Sign In...');
        
        await driver.findElement(By.linkText('Sign in')).click();
        
        console.log('Typing email ', email, '...');
        
        await driver.findElement(By.name('phoneOrMailCheck')).click();
        await driver.findElement(By.name('phoneOrMailCheck')).sendKeys(email);
        
        await driver.findElement(By.id('buttonCheckEmail')).click();
        
        console.log('Continue...');
        
        await driver.findElement(By.name('confirmCode')).click();
        
        console.log('Triying wrong code 1234...');
        
        await driver.findElement(By.name('confirmCode')).sendKeys('1234');
        
        await driver.findElement(By.id('buttonConfirmCode')).click();
        await driver.sleep(2000);
        
        console.log('Codes generated for the email: ', email, ', ', code1, ', ', code2);
        console.log('Triying code 1...');
        
        await driver.findElement(By.name('confirmCode')).clear();
        await driver.findElement(By.name('confirmCode')).sendKeys(code1);
        await driver.findElement(By.id('buttonConfirmCode')).click();
        
        if (!!await driver.executeScript('return (document.querySelector("[class=\'error-message has--error\']") !== null)')) {
            console.log('Wrong code');
            console.log('Triying code 2...');
            await driver.findElement(By.name('confirmCode')).clear();
            await driver.findElement(By.name('confirmCode')).sendKeys(code2);
            await driver.findElement(By.id('buttonConfirmCode')).click();
        }
        
        await driver.sleep(2000);
        
        console.log('Skipping pop up...');
        await driver.findElement(By.css('.button--middleText')).click()
        await driver.sleep(2000);
        
        await driver.findElement(By.id('buttonCheckEmail')).click();
        await driver.sleep(2000);
        
        {
            const element = await driver.findElement(By.css('.menu__dropdownTitle'));
            await driver.actions({ bridge: true }).move({origin: element}).perform();
        }
        
        
        console.log('Navigating to Settings...');
        await driver.findElement(By.linkText('Settings')).click();
        await driver.sleep(2000);
        
        //LOG OUT
        console.log('Log out...');
        await driver.findElement(By.css('body > div.row > div.col.hyper-nav > a:nth-child(7)')).click();
        await driver.sleep(5000);
    });

    it('Sing In', async function() {
        //LOG IN
        console.log('Log in again...');
        await driver.findElement(By.linkText('Sign in')).click();
        
        await driver.sleep(2000);
        
        console.log('Typing the email...');
        await driver.findElement(By.name("phoneOrMailCheck")).click();
        await driver.findElement(By.name("phoneOrMailCheck")).sendKeys(email);
        await driver.findElement(By.id("buttonCheckEmail")).click();
        
        console.log('Generating login codes...');

        let date = changeTimezone(new Date(), 'America/Toronto');
        let dateFirst = date.toJSON().split('T').join(' ').substr(0, 15);
        let dateSecond = (new Date(date.getTime() - 60 * 10 * 1000)).toJSON().split('T').join(' ').substr(0, 15);

        let code1 = generateCode(email, dateFirst, 6);
        let code2 = generateCode(email, dateSecond, 6);
        
        console.log('Checking access code...');
        await driver.findElement(By.name("otpCheck")).clear();
        await driver.findElement(By.name("otpCheck")).sendKeys(code1);
        await driver.findElement(By.id("buttonCheckOtp")).click()
        
        if (!!await driver.executeScript('return (document.querySelector("[class=\'error-message has--error\']") !== null)')) {
            console.log('Wrong code');
            console.log('Triying code 2...');
            await driver.findElement(By.name("otpCheck")).clear();
            await driver.findElement(By.name('otpCheck')).sendKeys(code2);
            await driver.findElement(By.id('buttonCheckOtp')).click();
        }
        
        await driver.sleep(2000);
        
        {
            const element = await driver.findElement(By.css('.menu__dropdownTitle'))
            await driver.actions({ bridge: true }).move({origin: element}).perform()
        }
        
        console.log('Navigating to Settings...')
        await driver.findElement(By.linkText('Settings')).click();
        
        
        await driver.findElement(By.linkText('Purge my account information')).click();
        
        await driver.sleep(2000);
        
        console.log('Purging the account...');
        await driver.findElement(By.name('submit')).click();

        await driver.sleep(5000);
    });
});
